config/routes.rb
Rails.application.routes.draw do
  resources :grocery_lists, only: [:index]
  resources :recipes, only: [:create, :edit, :update, :destroy, :index]
  resources :ingredients, path: "ingredients/:parent_list_type/:parent_list_id"

  # post "/ingredients/:parent_list_type/:parent_list_id", controller: :ingredients, action: :create, as: :ingredients
  # get "/ingredients/:parent_list_type/:parent_list_id", controller: :ingredients, action: :index
  post "/recipes/:id/grocery_lists/:grocery_list_id", controller: :recipes, action: :add_recipe_ingredients, as: :add_ingredients
  # delete "/recipes/:id/grocery_lists/:grocery_list_id/:id", controller: :recipes, action: :destroy, as: :ingredient

  post "/grocery_list/send_to_wunderlist", controller: :grocery_lists, action: :send_items_to_wunderlist, as: :post_to_wunderlist

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grocery_list.rb
require "httparty"

WUNDERLIST_URI = "http://a.wunderlist.com/api/v1/tasks"
LIST_ID = 140067646

class GroceryList < ApplicationRecord
  has_many :ingredients, as: :parent_list

  def consolidate_ingredients!
    self.ingredients.each do |ingredient_a|
      self.ingredients.each do |ingredient_b|
        if ingredient_a != ingredient_b
          if ingredient_a.name == ingredient_b.name && ingredient_a.unit == ingredient_b.unit
            ingredient_a.quantity += ingredient_b.quantity unless ingredient_a.destroyed? || ingredient_b.destroyed?
            ingredient_a.save!
            self.ingredients.delete(ingredient_b)
            Ingredient.delete(ingredient_b.id)
          end
        end
      end
    end
    self.save
  end

  def send_to_wunderlist
    headers = {"X-Client-ID": ENV['CLIENT_ID'], "X-Access-Token": ENV['ACCESS_TOKEN'], "Content-Type": "application/json"}
    self.ingredients.each do |ingredient|
      post_body = {
        "list_id": LIST_ID,
        "title": "#{ingredient.quantity} #{ingredient.name}"
      }
      response = HTTParty.post(WUNDERLIST_URI, headers: headers, body: post_body.to_json, :debug_output => $stdout)
      if !response.success?
        return "Unable to post to wunderlist!"
      end
    end
    return "Success"
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :parent_list, polymorphic: true
  validates :name, presence: true, length: { maximum: 250 }
  validates :quantity, length: { maximum: 250 }
end

app/models/recipe.rb
require "grocery_list"

class Recipe < ApplicationRecord
  has_many :ingredients, as: :parent_list
  validates :name, presence: true, length: { maximum: 200 }

  def add_all_ingredients_to(grocery_list_id)
    grocery_list = ::GroceryList.find_by(id: grocery_list_id)
    self.ingredients.each do |ingredient|
      grocery_ingredient = ingredient.dup
      grocery_list.ingredients << grocery_ingredient
      grocery_list.save
    end
    grocery_list.consolidate_ingredients!
    grocery_list.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
  def index
    @grocery_list = GroceryList.first
    @ingredient = Ingredient.new()
  end

  def update
    @grocery_list = GroceryList.find(params["id"])
    if @grocery_list.update(grocery_list_params)
      redirect_to grocery_lists_path
    else
      @message = "Unable to save your grocery_list"
    end
  end

  def send_items_to_wunderlist
    success = GroceryList.first.send_to_wunderlist
    if success == "Success"
      @success_message = "sent all items to wonderlist!"
    else
      @message = success
    end
    @grocery_list = GroceryList.first
    @ingredient = Ingredient.new()
    render :index
  end

  def grocery_list_params
    params.require(:grocery_list).permit(:name)
  end
end

app/controllers/ingredients_controller.rb
require 'pry'

class IngredientsController < ApplicationController
  before_action :find_parent_list

  def index
    @ingredient = Ingredient.new()
    @ingredients = @parent_list.ingredients
  end

  def show
    @ingredient = Ingredient.find(params["id"])
  end

  def new
    @ingredient = Ingredient.new()
    render :new
  end

  def edit
    @ingredient = Ingredient.find(params["id"])
  end

  def create
    @ingredient = @parent_list.ingredients.build(ingredient_params)
    @ingredient.save
    redirect_to :controller => @parent_list.class.to_s.underscore.pluralize.downcase, action: :index, id: @parent_list.id
  end

  def destroy
    Ingredient.find(params["id"]).destroy
    redirect_to ingredients_path(params[:parent_list_type], params[:parent_list_id])
  end

  def update
    @ingredient = Ingredient.find(params["id"])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path(@ingredient.parent_list_type, @ingredient.parent_list_id)
    else
      @message = "Unable to save your ingredient"
    end
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :quantity, :unit)
  end

  private
  def find_parent_list
    @klass = params[:parent_list_type].camelize.constantize
    @parent_list = @klass.find(params[:parent_list_id])
  end
end

app/controllers/recipes_controller.rb
require "pry"

class RecipesController < ApplicationController
  def index
    # there has to be a grocery list. check if one exists
    @grocery_list
    if GroceryList.count == 0
      @grocery_list = GroceryList.new({date: "Today"})
      @grocery_list.save
    else
      @grocery_list = GroceryList.first
    end
    @recipes = Recipe.all.reverse
  end

  def show
    @recipe = Recipe.find(params["id"])
  end

  def new
    @recipe = Recipe.new()
    render :new
  end

  def edit
    @recipe = Recipe.find(params["id"])
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, flash: { success: "Recipe created" }
    else
      render :index
    end
  end

  def destroy
    Recipe.find(params["id"]).destroy
    redirect_to recipes_path
  end

  def update
    @recipe = Recipe.find(params["id"])
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      @message = "Unable to save your recipe"
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :url)
  end

  def add_recipe_ingredients
    recipe = Recipe.find(params["id"])
    grocery_list = GroceryList.find(params["grocery_list_id"])
    recipe.add_all_ingredients_to(grocery_list.id)
    @recipes = Recipe.all.reverse
    @grocery_list = grocery_list
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grocery_lists_helper.rb
module GroceryListsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/grocery_lists/index.html.erb
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<% if @success_message %>
  <div class="alert alert-success">
    <%= @success_message %>
  </div>
<% end %>
<h1>Grocery List</h1>

<ul>
  <% if @grocery_list.ingredients.length > 0 %>
    <% @grocery_list.ingredients.each do |ingredient| %>
      <li>
        <%= "%g" % ("%.2f" % ingredient.quantity) %>
        <%= ingredient.unit %>
        <%= ingredient.name %>
        <%= link_to "remove ingredient", ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id), method: :delete %>
        <%= link_to "edit ingredient", edit_ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id) %>
      </li>
    <% end %>
  <% else %>
    <p>
      No ingredients
    </p>
  <% end %>
</ul>
<%= link_to "Send items to Wunderlist!", post_to_wunderlist_path, method: :post %>
<div class="row">
  <div class="col-sm-3">
    <%= form_for @ingredient, url: ingredients_path(parent_list_type: "grocery_list", parent_list_id: @grocery_list.id) do |f| %>

      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :quantity, class: "control-label" %>
        <%= f.text_field :quantity, class: "form-control" %>
      </div>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>
<%= link_to "Recipes", recipes_path %>

app/views/ingredients/edit.html.erb
<% @ingredient.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>

<% if @parent_list.class == GroceryList %>
  <h1>Grocery List</h1>
<% else %>
  <h1>Ingredients for <%= @parent_list.name%></h1>
<% end %>

<ul>
  <% @parent_list.ingredients.each do |ingredient| %>

    <% if @ingredient == ingredient %>
      <%= form_for @ingredient, url: ingredient_path(parent_list_type: ingredient.parent_list_type, parent_list_id: ingredient.parent_list_id, id: ingredient.id) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :quantity, class: "control-label" %>
          <%= f.text_field :quantity, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :unit, class: "control-label" %>
          <%= f.text_field :unit, class: "form-control" %>
        </div>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <li>
        <%= "%g" % ("%.2f" % ingredient.quantity) %>
        <%= ingredient.unit %>
        <%= ingredient.name %>
        <%= link_to "remove", ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id), method: :delete %> |
        <%= link_to "edit", edit_ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id) %>
      </li>
    <% end %>

  <% end %>
</ul>

<%= link_to "Back to recipes", recipes_path %>

<% if @ingredient.parent_list_type == "recipe" %>
  <%= link_to "Back to Recipe", recipe_path(@ingredient.recipe.id) %> |
<% end %>
<%= link_to "Grocery List", grocery_lists_path %>

app/views/ingredients/index.html.erb
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<% if @parent_list.class == GroceryList %>
  <h1>Grocery List</h1>
<% else %>
  <h1>Ingredients for <%= @parent_list.name%></h1>
<% end %>
<ul>
  <% if @ingredients.length > 0 %>
    <% @ingredients.each do |ingredient| %>
      <li>
        <%= "%g" % ("%.2f" % ingredient.quantity) %>
        <%= ingredient.unit %>
        <%= ingredient.name %>
        <%= link_to "remove", ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id), method: :delete %> |
        <%= link_to "edit", edit_ingredient_path(ingredient.parent_list_type, ingredient.parent_list_id, ingredient.id) %>
      </li>
    <% end %>
  <% else %>
    <p>
      No ingredients
    </p>
  <% end %>
  <% @ingredient.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
  <% end %>
</ul>
<div class="row">
  <div class="col-sm-3">
    <%= form_for @ingredient, url: ingredients_path(parent_list_type: "recipe", parent_list_id: @parent_list.id) do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :quantity, class: "control-label" %>
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :unit, class: "control-label" %>
      <%= f.text_field :unit, class: "form-control" %>
    </div>

    <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-sm-3">
  </div>
  <div class="col-sm-3">
  </div>
</div>


<%= link_to "Back to recipes", recipes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryListify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/edit.html.erb
<% @recipe.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>

<%= form_for @recipe do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <%= f.submit "Update", class: "btn btn-primary" %>

<% end %>

app/views/recipes/index.html.erb
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<h1>Your Recipes</h1>
<ul>
  <% @recipes.each do |recipe| %>
    <li style="list-style-type: none;">
      <h3><%= recipe.name %></h3>
      <%= link_to "edit", edit_recipe_path(recipe.id) %> |
      <%= link_to "ingredients", ingredients_path("Recipe", recipe.id) %> |
      <%= link_to "delete recipe", recipe_path(recipe.id), method: :delete %> |
      <%= link_to "Add ingredients to Grocery List", add_ingredients_path(recipe.id, @grocery_list.id), method: :post %>
      <br />
      <% if recipe.url %>
        Source:
        <% if recipe.url.start_with?("http") %>
          <%= link_to "Link", recipe.url %>
        <% else %>
          <%= recipe.url %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<hr />
<div class="row">
  <div class="col-sm-3">
    <p>
      Add a Recipe
      <%= form_for(:recipe) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :source, class: "control-label" %>
          <%= f.text_field :url, class: "form-control" %>
        </div>

        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Grocery List", grocery_lists_path %>
    </p>
  </div>
  <div class="col-sm-3">
  </div>
  <div class="col-sm-3">
  </div>
</div>